services:
  speedtest_aio_rpi:
    build:
      context: .
      dockerfile: Dockerfile-speedtest-RPi
    image: speedtest_aio_rpi:latest
    volumes:
      - speedtest-storage-rpi:/app/db
    container_name: speedtest_aio_rpi
    network_mode: "bridge"
  speedtest_grafana_rpi:
    build:
      context: .
      dockerfile: Dockerfile-grafana
    image: speedtest_grafana_rpi:latest
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
    volumes:
      - grafana-storage-rpi:/var/lib/grafana
      - speedtest-storage-rpi:/app/db
    depends_on:
      - speedtest_aio_rpi
    container_name: speedtest_grafana_rpi
    network_mode: "bridge"
    ports:
      - "3000:3000"
volumes:
  speedtest-storage-rpi:
  grafana-storage-rpi:
