##################
### BASE IMAGE ###
##################

ARG PYTHON_VER=3.10

FROM python:${PYTHON_VER}-alpine AS base
LABEL prune=true

WORKDIR /app

RUN apk --update add gcc build-base libffi-dev
RUN pip install poetry
RUN poetry config virtualenvs.create false

COPY pyproject.toml .

RUN poetry install --no-dev

##################
### TEST IMAGE ###
##################

FROM base AS test
LABEL prune=true

RUN poetry install

COPY . .

RUN echo '-->Running Flake8' && \
    flake8 . && \
    echo '-->Running Black' && \
    black --check --diff . && \
    echo '-->Running isort' && \
    find . -name '*.py' | xargs isort && \
    echo '-->Running Pylint' && \
    find . -name '*.py' | xargs pylint --rcfile=pyproject.toml && \
    echo '-->Running pydocstyle' && \
    pydocstyle . --config=pyproject.toml && \
    echo '-->Running Bandit' && \
    bandit --recursive ./ --configfile pyproject.toml

###################
### FINAL IMAGE ###
###################

FROM python:${PYTHON_VER}-alpine

ARG PYTHON_VER

RUN apk --update add busybox-suid speedtest-cli supercronic

RUN ln -snf /usr/share/zoneinfo/UTC /etc/localtime

WORKDIR /app

COPY entrypoint.sh /run/
RUN chmod 755 /run/entrypoint.sh

RUN addgroup docker && adduser -s /bin/false -S -D -H docker -G docker

COPY crontab /app/
COPY speedtest_aio/*.py /app/
RUN mkdir -p /app/db
RUN mkdir -p /app/log/
RUN chown -R docker:docker /app

USER docker

ENTRYPOINT ["/run/entrypoint.sh"]
