FROM grafana/grafana:10.2.7

COPY --chown=grafana:root grafana/datasource.yml /etc/grafana/provisioning/datasources/
COPY --chown=grafana:root grafana/dashboard.yml /etc/grafana/provisioning/dashboards/
COPY --chown=grafana:root grafana/grafana_dashboard.json /etc/grafana/provisioning/dashboards/
