apiVersion: 1
datasources:
  - name: Speedtest Database
    type: frser-sqlite-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      path: /var/lib/db/speedtest_database.sqlite
