{
 "title": "Speedtest",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "queryText": "SELECT\n  timestamp AS \"time\",\n  download AS \"Download Throughput\"\nFROM speedtest\nORDER BY timestamp",
     "rawQueryText": "SELECT\n  timestamp AS \"time\",\n  download AS \"Download Throughput\"\nFROM speedtest\nORDER BY timestamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT\n  timestamp AS \"time\",\n  upload AS \"Upload Throughput\"\nFROM speedtest\nORDER BY timestamp",
     "rawQueryText": "SELECT\n  timestamp AS \"time\",\n  upload AS \"Upload Throughput\"\nFROM speedtest\nORDER BY timestamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  timestamp AS \"time\",\n  max(download) AS \"Max\"\nFROM speedtest\nORDER BY timestamp",
     "rawQueryText": "SELECT\n  timestamp AS \"time\",\n  max(download) AS \"Max\"\nFROM speedtest\nORDER BY timestamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT\n  timestamp AS \"time\",\n  min(download) AS \"Min\"\nFROM speedtest\nORDER BY timestamp",
     "rawQueryText": "SELECT\n  timestamp AS \"time\",\n  min(download) AS \"Min\"\nFROM speedtest\nORDER BY timestamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT\n  timestamp AS \"time\",\n  avg(download) AS \"Average\"\nFROM speedtest\nORDER BY timestamp",
     "rawQueryText": "SELECT\n  timestamp AS \"time\",\n  avg(download) AS \"Average\"\nFROM speedtest\nORDER BY timestamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  timestamp AS \"time\",\n  max(upload) AS \"Max\"\nFROM speedtest\nORDER BY timestamp",
     "rawQueryText": "SELECT\n  timestamp AS \"time\",\n  max(upload) AS \"Max\"\nFROM speedtest\nORDER BY timestamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT\n  timestamp AS \"time\",\n  min(upload) AS \"Min\"\nFROM speedtest\nORDER BY timestamp",
     "rawQueryText": "SELECT\n  timestamp AS \"time\",\n  min(upload) AS \"Min\"\nFROM speedtest\nORDER BY timestamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT\n  timestamp AS \"time\",\n  avg(upload) AS \"Average\"\nFROM speedtest\nORDER BY timestamp",
     "rawQueryText": "SELECT\n  timestamp AS \"time\",\n  avg(upload) AS \"Average\"\nFROM speedtest\nORDER BY timestamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "queryText": "SELECT\n  timestamp AS \"time\",\n  ping\nFROM speedtest\nORDER BY timestamp",
     "rawQueryText": "SELECT\n  timestamp AS \"time\",\n  ping\nFROM speedtest\nORDER BY timestamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  timestamp AS \"time\",\n  min(ping) AS \"Best\"\nFROM speedtest\nORDER BY timestamp",
     "rawQueryText": "SELECT\n  timestamp AS \"time\",\n  min(ping) AS \"Best\"\nFROM speedtest\nORDER BY timestamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT\n  timestamp AS \"time\",\n  max(ping) AS \"Worst\"\nFROM speedtest\nORDER BY timestamp",
     "rawQueryText": "SELECT\n  timestamp AS \"time\",\n  max(ping) AS \"Worst\"\nFROM speedtest\nORDER BY timestamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT\n  timestamp AS \"time\",\n  avg(ping) AS \"Average\"\nFROM speedtest\nORDER BY timestamp",
     "rawQueryText": "SELECT\n  timestamp AS \"time\",\n  avg(ping) AS \"Average\"\nFROM speedtest\nORDER BY timestamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Test Results",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT\n  timestamp AS \"time\", download, upload, ping, server_id, server_host\nFROM speedtest\nORDER BY timestamp DESC",
     "rawQueryText": "SELECT\n  timestamp AS \"time\", download, upload, ping, server_id, server_host\nFROM speedtest\nORDER BY timestamp DESC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}